FROM quay.io/fedora/fedora-bootc:41


RUN dnf install -y https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
RUN dnf install -y https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
#RUN dnf config-manager setopt fedora-cisco-openh264.enabled=1
RUN dnf list



# https://download1.rpmfusion.org/free/fedora/RPM-GPG-KEY-rpmfusion-free-fedora-2020
# https://download1.rpmfusion.org/nonfree/fedora/RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020
# https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-41.noarch.rpm
# https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-41.noarch.rpm
# RUN <<EOF
#     dnf install -y
#         kmodtool \\
#         akmods
#         mokutil
#         openssl
#         akmod-nvidia
#         xorg-x11-drv-nvidia-cuda
# EOF