name: Build bootc container based on pr to latest

on:
  pull_request:
    branches:
      - main
  schedule:

env:
  REGISTRY_USER: rh-ee-chbutler
  IMAGE_REGISTRY: quay.io

jobs:
  buildlatest:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Quay.io
      uses: redhat-actions/podman-login@v1
      with:
        username: ${{ env.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        registry: ${{ env.IMAGE_REGISTRY }}

    - name: Log in to registry.redhat.io
      uses: redhat-actions/podman-login@v1
      with:
        username: ${{ env.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        registry: registry.redhat.io