name: Build bootc container based on pr to latest

on:
  pull_request:
    branches:
      - main
env:
  REGISTRY_USER: rh-ee-chbutler
  IMAGE_REGISTRY: quay.io
  IMAGE: fedora

jobs:
  buildlatest:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Quay.io
      uses: redhat-actions/podman-login@v1
      with:
        username: ${{ env.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        registry: ${{ env.IMAGE_REGISTRY }}

    - name: Log in to registry.redhat.io
      uses: redhat-actions/podman-login@v1
      with:
        username: ${{ env.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        registry: registry.redhat.io


    - name: Build Image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: "${{ env.IMAGE }}"
        tags: latest ${{ github.sha }}
        containerfiles: |
         ./bootc/Containerfile

    - name: Install Cosign
      uses: sigstore/cosign-installer@v3.7.0
    
    - name: Get image sha
      id: imagesha
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ env.IMAGE }}
        tags: latest ${{ github.sha }}
        registry: quay.io/${{ env.REGISTRY_USER }}
    - name: Get image digest
      run: echo "sha_digest=`podman images localhost/${{ env.IMAGE }}:latest --digests  --format '{{.Digest}}'`" >> $GITHUB_OUTPUT

    - name: Sign using oidc
      run: cosign sign -y -a sha=${{ github.sha }} -a run_id=${{github.run_id}} -a run_attempt="$GITHUB_RUN_ATTEMPT" quay.io/${{ env.REGISTRY_USER }}/${{ env.IMAGE }}:${{ steps.imagesha.outputs.sha_digest }}


